name: E2E Tests

on: 
  workflow_dispatch: 
    inputs:
      base_url:
        description: 'Escolha o ambiente de sua preferencia(local, homolog, production)'
        required: true
        default: 'http://localhost:3000'
      browser:
        description: 'Escolha o navegador de sua preferência'
        required: true
        default: chrome

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          BASE_URL: ${{ github.event.inputs.base_url }}
        with:
          start: npm start
          browser: ${{ github.event.inputs.browser }}
      
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-${{ github.event.inputs.browser }}
          path: cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ github.event.inputs.browser }}
          path: cypress/videos
